server.port=8080

spring.datasource.url=jdbc:h2:mem:sms_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

app.jwt.secret=9a6747f3c758d09e18184f479a86a60e0a5c0b029ff6d2466085a6a4e320f782c5a176ebc18a287be1be08c7349b1479fa457788417c83f
app.jwt.expiration-ms=86400000
